import type { Demo, Campaign, Release } from '../types'

export const SEED_DEMOS: Demo[] = [
  {
    id: '1',
    artist: 'SOMMA',
    song: 'Body on Fire',
    genre: 'House',
    bpm: 126,
    key: 'A min',
    source: 'TikTok',
    viralScore: 9,
    status: 'sign',
    notes: 'Huge hook, already 2M views on TikTok. Build drop is insane. Potential crossover.',
    tags: ['hook', 'crossover', 'festival'],
    dateAdded: '2025-04-20',
    duration: '0:42',
  },
  {
    id: '2',
    artist: 'Sidepiece',
    song: 'Bright Eyes Edit',
    genre: 'Tech House',
    bpm: 130,
    key: 'F# min',
    source: 'TikTok',
    viralScore: 9,
    status: 'sign',
    notes: 'Engineered for virality. Short loop, insane groove. TikTok template ready.',
    tags: ['tech house', 'TikTok', 'groove'],
    dateAdded: '2025-04-17',
    duration: '0:31',
  },
  {
    id: '3',
    artist: 'Lumix',
    song: 'Speed Run',
    genre: 'Hyperpop',
    bpm: 160,
    key: 'D maj',
    source: 'Instagram',
    viralScore: 8,
    status: 'new',
    notes: 'Just came in. Energy through the roof. Needs proper A&R session.',
    tags: ['hyperpop', 'speed', 'new'],
    dateAdded: '2025-04-21',
    duration: '0:28',
  },
  {
    id: '4',
    artist: 'Marza',
    song: 'Brazil Edit',
    genre: 'EDM',
    bpm: 128,
    key: 'G maj',
    source: 'TikTok',
    viralScore: 8,
    status: 'new',
    notes: 'Brazil sound trending hard. Taps right into the moment.',
    tags: ['trending', 'Brazil', 'moment'],
    dateAdded: '2025-04-21',
    duration: '0:37',
  },
  {
    id: '5',
    artist: 'Eli Fur',
    song: 'You Are So High',
    genre: 'Melodic House',
    bpm: 122,
    key: 'E min',
    source: 'Spotify',
    viralScore: 8,
    status: 'review',
    notes: 'Already charting on Beatport. Sound design is premium.',
    tags: ['beatport', 'sound design'],
    dateAdded: '2025-04-19',
    duration: '0:55',
  },
  {
    id: '6',
    artist: 'Oskar Med K',
    song: 'Untitled Loop',
    genre: 'House',
    bpm: 124,
    key: 'C# min',
    source: 'Email',
    viralScore: 8,
    status: 'review',
    notes: 'Loop is hypnotic. Needs structure but the energy is there.',
    tags: ['loop', 'hypnotic', 'raw'],
    dateAdded: '2025-04-21',
    duration: '0:38',
  },
  {
    id: '7',
    artist: 'Falden',
    song: "I Don't Want to Know",
    genre: 'Indie Electronic',
    bpm: 118,
    key: 'B min',
    source: 'SoundCloud',
    viralScore: 7,
    status: 'hold',
    notes: 'Promising but needs more punch in the drop. Revisit in 2 weeks.',
    tags: ['indie', 'needs work'],
    dateAdded: '2025-04-18',
    duration: '0:49',
  },
  {
    id: '8',
    artist: 'Michel Bibi',
    song: 'Minimal Session',
    genre: 'Minimal Tech',
    bpm: 132,
    key: 'A min',
    source: 'Beatport',
    viralScore: 7,
    status: 'review',
    notes: 'European minimal energy. Good for DJ sets, unknown TikTok potential.',
    tags: ['minimal', 'DJ', 'European'],
    dateAdded: '2025-04-16',
    duration: '1:02',
  },
  {
    id: '9',
    artist: 'Ian Asher',
    song: 'Walk Away',
    genre: 'Pop Electronic',
    bpm: 115,
    key: 'C maj',
    source: 'Email',
    viralScore: 6,
    status: 'pass',
    notes: 'Well produced but too safe. No clear viral angle. Pass for now.',
    tags: ['safe', 'no hook'],
    dateAdded: '2025-04-15',
    duration: '0:44',
  },
  {
    id: '10',
    artist: 'Avicii',
    song: 'Original Re-record',
    genre: 'EDM',
    bpm: 128,
    key: 'F maj',
    source: 'Internal',
    viralScore: 7,
    status: 'ref',
    notes: 'Internal reference for production direction. Not for signing.',
    tags: ['reference', 'internal', 'EDM'],
    dateAdded: '2025-04-14',
    duration: '1:15',
  },
]

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: 'c1',
    name: 'Body on Fire — TikTok Launch',
    artist: 'SOMMA',
    type: 'TikTok',
    status: 'production',
    budget: 5000,
    targetPlatform: ['TikTok', 'Instagram'],
    linkedDemoId: '1',
    notes: 'Target dance and DJ communities. 15s loop ready. Creator seeding phase next week.',
    dueDate: '2025-05-01',
  },
  {
    id: 'c2',
    name: 'Bright Eyes Edit — Full Launch',
    artist: 'Sidepiece',
    type: 'Full Launch',
    status: 'brief',
    budget: 8000,
    targetPlatform: ['TikTok', 'Spotify', 'Beatport'],
    linkedDemoId: '2',
    notes: 'Festival season push. Target tech house crowd + mainstream TikTok dance trend.',
    dueDate: '2025-05-15',
  },
  {
    id: 'c3',
    name: 'Brazil Edit — Trend Ride',
    artist: 'Marza',
    type: 'Organic',
    status: 'idea',
    budget: 2000,
    targetPlatform: ['TikTok'],
    linkedDemoId: '4',
    notes: 'Capitalize on Brazil sound trend. Organic-first, then paid amplification.',
    dueDate: '2025-04-28',
  },
]

export const SEED_RELEASES: Release[] = [
  {
    id: 'r1',
    artist: 'SOMMA',
    title: 'Body on Fire',
    type: 'Single',
    releaseDate: '2025-05-10',
    status: 'mastering',
    platforms: ['Spotify', 'Apple Music', 'Beatport', 'TikTok'],
    linkedDemoId: '1',
  },
  {
    id: 'r2',
    artist: 'Sidepiece',
    title: 'Bright Eyes Edit',
    type: 'Single',
    releaseDate: '2025-05-24',
    status: 'planned',
    platforms: ['Spotify', 'Apple Music', 'Beatport'],
    linkedDemoId: '2',
  },
  {
    id: 'r3',
    artist: 'RTF Various Artists',
    title: 'RTF Vol. 1 — Spring Compilation',
    type: 'EP',
    releaseDate: '2025-06-15',
    status: 'planned',
    platforms: ['Spotify', 'Apple Music', 'Beatport', 'SoundCloud'],
  },
]

export const STATUS_LABELS: Record<string, string> = {
  new: 'New',
  review: 'In Review',
  hold: 'On Hold',
  sign: 'Sign',
  pass: 'Pass',
  ref: 'Reference',
}

export const PIPELINE_COLUMNS = [
  { id: 'new', label: 'New', color: '#3B82F6' },
  { id: 'review', label: 'In Review', color: '#BA7517' },
  { id: 'hold', label: 'On Hold', color: '#7C3AED' },
  { id: 'sign', label: 'Sign', color: '#16a34a' },
  { id: 'pass', label: 'Pass', color: '#E24B4A' },
  { id: 'ref', label: 'Reference', color: '#888780' },
]
